### ISSUE TITLE
Notifiy users of new gamer os releases via a steam pop-up

### ISSUE THREAD

**Issue by ChojinDSL** [ChimeraOS/frzr#16]
Some events create a pop-up in steam big picture mode. Would it be possible to use that functionality to inform the user that a new gamer os release is ready?

**Comment by sharkwouter** [comment]
I like this idea and I think it is possible, the hard part is figuring out how to implement it. I think we can make steam show that there is an update in about the same way we show the update is complete, but the hard part here is that the user will get the option to restart and update the system, which we currently do not support.

@alkazar what do you think? Should we make frzr able to update the system on shutdown instead of while running? I think that would probably be the cleanest solution, since SteamOS updates in the same way.

**Comment by alkazar** [comment]
When the release is downloaded we already notify the user. We cannot create Steam popups with custom messages.

If you want to be notified when on new releases you can become a member of the gamer-os group on Steam.

I dont want to make people wait for updates on shutdown, although we could introduce some UI that appears if an update download is in progress and ask if users want to complete it before shutting down.
I question the value of that though.

I think this problem should be smoothed over now that we resume partial downloads.

**Comment by sharkwouter** [comment]
Good points. Can you leave this open and assign it to me? I may not be able to look into this very soon, but I am interested in trying to figure out which commands Steam uses when you try to make it update the system and if I can make a notification appear that there is a new update. Maybe we can make use of it at some point in the future and make it execute a specific script, like showing the changelog.

**Comment by ChojinDSL** [comment]
If it's not possible to create a steam pop-up with a custom message. What about using steam-buddy as a workaround? e.g. When you log in to steambuddy that there is a little message there that a update has been downloaded and is waiting for a reboot to apply?

**Comment by alkazar** [comment]
That could work.

**Comment by sharkwouter** [comment]
I haven't managed to figure this out so far and I won't be working on this anytime soon, so I'm unassigning myself.

**Comment by alkazar** [comment]
Big Picture is on the way out, so closing in favour of https://github.com/ChimeraOS/chimeraos/issues/338
